// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/rfizzle/go-starter/internal/entity"
)

// HealthLivenessHandlerFunc turns a function with the right signature into a health liveness handler
type HealthLivenessHandlerFunc func(HealthLivenessParams, entity.Entity) middleware.Responder

// Handle executing the request and returning a response
func (fn HealthLivenessHandlerFunc) Handle(params HealthLivenessParams, principal entity.Entity) middleware.Responder {
	return fn(params, principal)
}

// HealthLivenessHandler interface for that can handle valid health liveness params
type HealthLivenessHandler interface {
	Handle(HealthLivenessParams, entity.Entity) middleware.Responder
}

// NewHealthLiveness creates a new http.Handler for the health liveness operation
func NewHealthLiveness(ctx *middleware.Context, handler HealthLivenessHandler) *HealthLiveness {
	return &HealthLiveness{Context: ctx, Handler: handler}
}

/*
	HealthLiveness swagger:route GET /healthz/liveness health healthLiveness

Liveness probe for kubernetes health check. Returns 200 if the service is alive.

Liveness probe
*/
type HealthLiveness struct {
	Context *middleware.Context
	Handler HealthLivenessHandler
}

func (o *HealthLiveness) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewHealthLivenessParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal entity.Entity
	if uprinc != nil {
		principal = uprinc.(entity.Entity) // this is really a entity.Entity, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
