// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// HealthLivenessOKCode is the HTTP code returned for type HealthLivenessOK
const HealthLivenessOKCode int = 200

/*
HealthLivenessOK success

swagger:response healthLivenessOK
*/
type HealthLivenessOK struct {
}

// NewHealthLivenessOK creates HealthLivenessOK with default headers values
func NewHealthLivenessOK() *HealthLivenessOK {

	return &HealthLivenessOK{}
}

// WriteResponse to the client
func (o *HealthLivenessOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
