// Code generated by go-swagger; DO NOT EDIT.

// Package api Application
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api
//	Version: 0.2.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package api
