// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	models "github.com/rfizzle/go-starter/pkg/schema"
)

// NewAuthLoginV1Params creates a new AuthLoginV1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAuthLoginV1Params() *AuthLoginV1Params {
	return &AuthLoginV1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewAuthLoginV1ParamsWithTimeout creates a new AuthLoginV1Params object
// with the ability to set a timeout on a request.
func NewAuthLoginV1ParamsWithTimeout(timeout time.Duration) *AuthLoginV1Params {
	return &AuthLoginV1Params{
		timeout: timeout,
	}
}

// NewAuthLoginV1ParamsWithContext creates a new AuthLoginV1Params object
// with the ability to set a context for a request.
func NewAuthLoginV1ParamsWithContext(ctx context.Context) *AuthLoginV1Params {
	return &AuthLoginV1Params{
		Context: ctx,
	}
}

// NewAuthLoginV1ParamsWithHTTPClient creates a new AuthLoginV1Params object
// with the ability to set a custom HTTPClient for a request.
func NewAuthLoginV1ParamsWithHTTPClient(client *http.Client) *AuthLoginV1Params {
	return &AuthLoginV1Params{
		HTTPClient: client,
	}
}

/*
AuthLoginV1Params contains all the parameters to send to the API endpoint

	for the auth login v1 operation.

	Typically these are written to a http.Request.
*/
type AuthLoginV1Params struct {

	// Body.
	Body *models.LoginRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the auth login v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthLoginV1Params) WithDefaults() *AuthLoginV1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the auth login v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthLoginV1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the auth login v1 params
func (o *AuthLoginV1Params) WithTimeout(timeout time.Duration) *AuthLoginV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the auth login v1 params
func (o *AuthLoginV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the auth login v1 params
func (o *AuthLoginV1Params) WithContext(ctx context.Context) *AuthLoginV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the auth login v1 params
func (o *AuthLoginV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the auth login v1 params
func (o *AuthLoginV1Params) WithHTTPClient(client *http.Client) *AuthLoginV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the auth login v1 params
func (o *AuthLoginV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the auth login v1 params
func (o *AuthLoginV1Params) WithBody(body *models.LoginRequest) *AuthLoginV1Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the auth login v1 params
func (o *AuthLoginV1Params) SetBody(body *models.LoginRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *AuthLoginV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
