// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAuthLogoutParams creates a new AuthLogoutParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAuthLogoutParams() *AuthLogoutParams {
	return &AuthLogoutParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAuthLogoutParamsWithTimeout creates a new AuthLogoutParams object
// with the ability to set a timeout on a request.
func NewAuthLogoutParamsWithTimeout(timeout time.Duration) *AuthLogoutParams {
	return &AuthLogoutParams{
		timeout: timeout,
	}
}

// NewAuthLogoutParamsWithContext creates a new AuthLogoutParams object
// with the ability to set a context for a request.
func NewAuthLogoutParamsWithContext(ctx context.Context) *AuthLogoutParams {
	return &AuthLogoutParams{
		Context: ctx,
	}
}

// NewAuthLogoutParamsWithHTTPClient creates a new AuthLogoutParams object
// with the ability to set a custom HTTPClient for a request.
func NewAuthLogoutParamsWithHTTPClient(client *http.Client) *AuthLogoutParams {
	return &AuthLogoutParams{
		HTTPClient: client,
	}
}

/*
AuthLogoutParams contains all the parameters to send to the API endpoint

	for the auth logout operation.

	Typically these are written to a http.Request.
*/
type AuthLogoutParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the auth logout params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthLogoutParams) WithDefaults() *AuthLogoutParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the auth logout params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuthLogoutParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the auth logout params
func (o *AuthLogoutParams) WithTimeout(timeout time.Duration) *AuthLogoutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the auth logout params
func (o *AuthLogoutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the auth logout params
func (o *AuthLogoutParams) WithContext(ctx context.Context) *AuthLogoutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the auth logout params
func (o *AuthLogoutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the auth logout params
func (o *AuthLogoutParams) WithHTTPClient(client *http.Client) *AuthLogoutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the auth logout params
func (o *AuthLogoutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AuthLogoutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
