// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AuthLogoutV1Reader is a Reader for the AuthLogoutV1 structure.
type AuthLogoutV1Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuthLogoutV1Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAuthLogoutV1OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /v1/auth/logout] AuthLogoutV1", response, response.Code())
	}
}

// NewAuthLogoutV1OK creates a AuthLogoutV1OK with default headers values
func NewAuthLogoutV1OK() *AuthLogoutV1OK {
	return &AuthLogoutV1OK{}
}

/*
AuthLogoutV1OK describes a response with status code 200, with default header values.

success
*/
type AuthLogoutV1OK struct {
}

// IsSuccess returns true when this auth logout v1 o k response has a 2xx status code
func (o *AuthLogoutV1OK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this auth logout v1 o k response has a 3xx status code
func (o *AuthLogoutV1OK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this auth logout v1 o k response has a 4xx status code
func (o *AuthLogoutV1OK) IsClientError() bool {
	return false
}

// IsServerError returns true when this auth logout v1 o k response has a 5xx status code
func (o *AuthLogoutV1OK) IsServerError() bool {
	return false
}

// IsCode returns true when this auth logout v1 o k response a status code equal to that given
func (o *AuthLogoutV1OK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the auth logout v1 o k response
func (o *AuthLogoutV1OK) Code() int {
	return 200
}

func (o *AuthLogoutV1OK) Error() string {
	return fmt.Sprintf("[POST /v1/auth/logout][%d] authLogoutV1OK ", 200)
}

func (o *AuthLogoutV1OK) String() string {
	return fmt.Sprintf("[POST /v1/auth/logout][%d] authLogoutV1OK ", 200)
}

func (o *AuthLogoutV1OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
