// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AuthLogoutReader is a Reader for the AuthLogout structure.
type AuthLogoutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AuthLogoutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAuthLogoutOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/auth/logout] AuthLogout", response, response.Code())
	}
}

// NewAuthLogoutOK creates a AuthLogoutOK with default headers values
func NewAuthLogoutOK() *AuthLogoutOK {
	return &AuthLogoutOK{}
}

/*
AuthLogoutOK describes a response with status code 200, with default header values.

success
*/
type AuthLogoutOK struct {
}

// IsSuccess returns true when this auth logout o k response has a 2xx status code
func (o *AuthLogoutOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this auth logout o k response has a 3xx status code
func (o *AuthLogoutOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this auth logout o k response has a 4xx status code
func (o *AuthLogoutOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this auth logout o k response has a 5xx status code
func (o *AuthLogoutOK) IsServerError() bool {
	return false
}

// IsCode returns true when this auth logout o k response a status code equal to that given
func (o *AuthLogoutOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the auth logout o k response
func (o *AuthLogoutOK) Code() int {
	return 200
}

func (o *AuthLogoutOK) Error() string {
	return fmt.Sprintf("[POST /api/v1/auth/logout][%d] authLogoutOK ", 200)
}

func (o *AuthLogoutOK) String() string {
	return fmt.Sprintf("[POST /api/v1/auth/logout][%d] authLogoutOK ", 200)
}

func (o *AuthLogoutOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
