// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AuthLogoutV1OKCode is the HTTP code returned for type AuthLogoutV1OK
const AuthLogoutV1OKCode int = 200

/*
AuthLogoutV1OK success

swagger:response authLogoutV1OK
*/
type AuthLogoutV1OK struct {
}

// NewAuthLogoutV1OK creates AuthLogoutV1OK with default headers values
func NewAuthLogoutV1OK() *AuthLogoutV1OK {

	return &AuthLogoutV1OK{}
}

// WriteResponse to the client
func (o *AuthLogoutV1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
