// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AuthLogoutOKCode is the HTTP code returned for type AuthLogoutOK
const AuthLogoutOKCode int = 200

/*
AuthLogoutOK success

swagger:response authLogoutOK
*/
type AuthLogoutOK struct {
}

// NewAuthLogoutOK creates AuthLogoutOK with default headers values
func NewAuthLogoutOK() *AuthLogoutOK {

	return &AuthLogoutOK{}
}

// WriteResponse to the client
func (o *AuthLogoutOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}
