// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	"github.com/rfizzle/go-starter/internal/entity"
)

// AuthLogoutV1HandlerFunc turns a function with the right signature into a auth logout v1 handler
type AuthLogoutV1HandlerFunc func(AuthLogoutV1Params, entity.Entity) middleware.Responder

// Handle executing the request and returning a response
func (fn AuthLogoutV1HandlerFunc) Handle(params AuthLogoutV1Params, principal entity.Entity) middleware.Responder {
	return fn(params, principal)
}

// AuthLogoutV1Handler interface for that can handle valid auth logout v1 params
type AuthLogoutV1Handler interface {
	Handle(AuthLogoutV1Params, entity.Entity) middleware.Responder
}

// NewAuthLogoutV1 creates a new http.Handler for the auth logout v1 operation
func NewAuthLogoutV1(ctx *middleware.Context, handler AuthLogoutV1Handler) *AuthLogoutV1 {
	return &AuthLogoutV1{Context: ctx, Handler: handler}
}

/*
	AuthLogoutV1 swagger:route POST /v1/auth/logout auth authLogoutV1

# Logout the current user

Invalidates an authenticated user's session and cookie
*/
type AuthLogoutV1 struct {
	Context *middleware.Context
	Handler AuthLogoutV1Handler
}

func (o *AuthLogoutV1) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewAuthLogoutV1Params()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal entity.Entity
	if uprinc != nil {
		principal = uprinc.(entity.Entity) // this is really a entity.Entity, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
