// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AuthCheckV1OKCode is the HTTP code returned for type AuthCheckV1OK
const AuthCheckV1OKCode int = 200

/*
AuthCheckV1OK success

swagger:response authCheckV1OK
*/
type AuthCheckV1OK struct {
}

// NewAuthCheckV1OK creates AuthCheckV1OK with default headers values
func NewAuthCheckV1OK() *AuthCheckV1OK {

	return &AuthCheckV1OK{}
}

// WriteResponse to the client
func (o *AuthCheckV1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// AuthCheckV1UnauthorizedCode is the HTTP code returned for type AuthCheckV1Unauthorized
const AuthCheckV1UnauthorizedCode int = 401

/*
AuthCheckV1Unauthorized unauthorized

swagger:response authCheckV1Unauthorized
*/
type AuthCheckV1Unauthorized struct {
}

// NewAuthCheckV1Unauthorized creates AuthCheckV1Unauthorized with default headers values
func NewAuthCheckV1Unauthorized() *AuthCheckV1Unauthorized {

	return &AuthCheckV1Unauthorized{}
}

// WriteResponse to the client
func (o *AuthCheckV1Unauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
