// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHealthReadinessParams creates a new HealthReadinessParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHealthReadinessParams() *HealthReadinessParams {
	return &HealthReadinessParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHealthReadinessParamsWithTimeout creates a new HealthReadinessParams object
// with the ability to set a timeout on a request.
func NewHealthReadinessParamsWithTimeout(timeout time.Duration) *HealthReadinessParams {
	return &HealthReadinessParams{
		timeout: timeout,
	}
}

// NewHealthReadinessParamsWithContext creates a new HealthReadinessParams object
// with the ability to set a context for a request.
func NewHealthReadinessParamsWithContext(ctx context.Context) *HealthReadinessParams {
	return &HealthReadinessParams{
		Context: ctx,
	}
}

// NewHealthReadinessParamsWithHTTPClient creates a new HealthReadinessParams object
// with the ability to set a custom HTTPClient for a request.
func NewHealthReadinessParamsWithHTTPClient(client *http.Client) *HealthReadinessParams {
	return &HealthReadinessParams{
		HTTPClient: client,
	}
}

/*
HealthReadinessParams contains all the parameters to send to the API endpoint

	for the health readiness operation.

	Typically these are written to a http.Request.
*/
type HealthReadinessParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the health readiness params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HealthReadinessParams) WithDefaults() *HealthReadinessParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the health readiness params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HealthReadinessParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the health readiness params
func (o *HealthReadinessParams) WithTimeout(timeout time.Duration) *HealthReadinessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the health readiness params
func (o *HealthReadinessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the health readiness params
func (o *HealthReadinessParams) WithContext(ctx context.Context) *HealthReadinessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the health readiness params
func (o *HealthReadinessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the health readiness params
func (o *HealthReadinessParams) WithHTTPClient(client *http.Client) *HealthReadinessParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the health readiness params
func (o *HealthReadinessParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *HealthReadinessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
