// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewHealthLivenessParams creates a new HealthLivenessParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHealthLivenessParams() *HealthLivenessParams {
	return &HealthLivenessParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHealthLivenessParamsWithTimeout creates a new HealthLivenessParams object
// with the ability to set a timeout on a request.
func NewHealthLivenessParamsWithTimeout(timeout time.Duration) *HealthLivenessParams {
	return &HealthLivenessParams{
		timeout: timeout,
	}
}

// NewHealthLivenessParamsWithContext creates a new HealthLivenessParams object
// with the ability to set a context for a request.
func NewHealthLivenessParamsWithContext(ctx context.Context) *HealthLivenessParams {
	return &HealthLivenessParams{
		Context: ctx,
	}
}

// NewHealthLivenessParamsWithHTTPClient creates a new HealthLivenessParams object
// with the ability to set a custom HTTPClient for a request.
func NewHealthLivenessParamsWithHTTPClient(client *http.Client) *HealthLivenessParams {
	return &HealthLivenessParams{
		HTTPClient: client,
	}
}

/*
HealthLivenessParams contains all the parameters to send to the API endpoint

	for the health liveness operation.

	Typically these are written to a http.Request.
*/
type HealthLivenessParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the health liveness params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HealthLivenessParams) WithDefaults() *HealthLivenessParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the health liveness params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HealthLivenessParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the health liveness params
func (o *HealthLivenessParams) WithTimeout(timeout time.Duration) *HealthLivenessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the health liveness params
func (o *HealthLivenessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the health liveness params
func (o *HealthLivenessParams) WithContext(ctx context.Context) *HealthLivenessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the health liveness params
func (o *HealthLivenessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the health liveness params
func (o *HealthLivenessParams) WithHTTPClient(client *http.Client) *HealthLivenessParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the health liveness params
func (o *HealthLivenessParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *HealthLivenessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
