// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/rfizzle/go-starter/pkg/schema"
)

// HealthReadinessReader is a Reader for the HealthReadiness structure.
type HealthReadinessReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HealthReadinessReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHealthReadinessOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 503:
		result := NewHealthReadinessServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /healthz/readiness] HealthReadiness", response, response.Code())
	}
}

// NewHealthReadinessOK creates a HealthReadinessOK with default headers values
func NewHealthReadinessOK() *HealthReadinessOK {
	return &HealthReadinessOK{}
}

/*
HealthReadinessOK describes a response with status code 200, with default header values.

success
*/
type HealthReadinessOK struct {
}

// IsSuccess returns true when this health readiness o k response has a 2xx status code
func (o *HealthReadinessOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this health readiness o k response has a 3xx status code
func (o *HealthReadinessOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this health readiness o k response has a 4xx status code
func (o *HealthReadinessOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this health readiness o k response has a 5xx status code
func (o *HealthReadinessOK) IsServerError() bool {
	return false
}

// IsCode returns true when this health readiness o k response a status code equal to that given
func (o *HealthReadinessOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the health readiness o k response
func (o *HealthReadinessOK) Code() int {
	return 200
}

func (o *HealthReadinessOK) Error() string {
	return fmt.Sprintf("[GET /healthz/readiness][%d] healthReadinessOK ", 200)
}

func (o *HealthReadinessOK) String() string {
	return fmt.Sprintf("[GET /healthz/readiness][%d] healthReadinessOK ", 200)
}

func (o *HealthReadinessOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewHealthReadinessServiceUnavailable creates a HealthReadinessServiceUnavailable with default headers values
func NewHealthReadinessServiceUnavailable() *HealthReadinessServiceUnavailable {
	return &HealthReadinessServiceUnavailable{}
}

/*
HealthReadinessServiceUnavailable describes a response with status code 503, with default header values.

Not available
*/
type HealthReadinessServiceUnavailable struct {
	Payload *models.ErrorResponse
}

// IsSuccess returns true when this health readiness service unavailable response has a 2xx status code
func (o *HealthReadinessServiceUnavailable) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this health readiness service unavailable response has a 3xx status code
func (o *HealthReadinessServiceUnavailable) IsRedirect() bool {
	return false
}

// IsClientError returns true when this health readiness service unavailable response has a 4xx status code
func (o *HealthReadinessServiceUnavailable) IsClientError() bool {
	return false
}

// IsServerError returns true when this health readiness service unavailable response has a 5xx status code
func (o *HealthReadinessServiceUnavailable) IsServerError() bool {
	return true
}

// IsCode returns true when this health readiness service unavailable response a status code equal to that given
func (o *HealthReadinessServiceUnavailable) IsCode(code int) bool {
	return code == 503
}

// Code gets the status code for the health readiness service unavailable response
func (o *HealthReadinessServiceUnavailable) Code() int {
	return 503
}

func (o *HealthReadinessServiceUnavailable) Error() string {
	return fmt.Sprintf("[GET /healthz/readiness][%d] healthReadinessServiceUnavailable  %+v", 503, o.Payload)
}

func (o *HealthReadinessServiceUnavailable) String() string {
	return fmt.Sprintf("[GET /healthz/readiness][%d] healthReadinessServiceUnavailable  %+v", 503, o.Payload)
}

func (o *HealthReadinessServiceUnavailable) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *HealthReadinessServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
