// Code generated by go-swagger; DO NOT EDIT.

package schema

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ErrorResponse error response
//
// swagger:model errorResponse
type ErrorResponse struct {

	// code
	// Maximum: 599
	// Minimum: 100
	Code int64 `json:"code,omitempty"`

	// data
	Data interface{} `json:"data,omitempty"`

	// message
	// Required: true
	Message *string `json:"message"`

	// status
	// Required: true
	// Enum: [error]
	Status *string `json:"status"`
}

// Validate validates this error response
func (m *ErrorResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ErrorResponse) validateCode(formats strfmt.Registry) error {
	if swag.IsZero(m.Code) { // not required
		return nil
	}

	if err := validate.MinimumInt("code", "body", m.Code, 100, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("code", "body", m.Code, 599, false); err != nil {
		return err
	}

	return nil
}

func (m *ErrorResponse) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("message", "body", m.Message); err != nil {
		return err
	}

	return nil
}

var errorResponseTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["error"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		errorResponseTypeStatusPropEnum = append(errorResponseTypeStatusPropEnum, v)
	}
}

const (

	// ErrorResponseStatusError captures enum value "error"
	ErrorResponseStatusError string = "error"
)

// prop value enum
func (m *ErrorResponse) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, errorResponseTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ErrorResponse) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this error response based on context it is used
func (m *ErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ErrorResponse) UnmarshalBinary(b []byte) error {
	var res ErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
