# This is our base swagger file and the primary mixin target.
# Everything in definitions|paths/*.yml will be mixed through
# and finally flattened into the actual swagger.yml in this dir.
swagger: "2.0"
info:
  title: Application
  version: '0.2.0'
consumes:
  - application/json
produces:
  - application/json
paths: {}
securityDefinitions:
  hasPermission:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://example.com
    tokenUrl: https://example.com
    scopes:
      auth:check: Check if the user is authenticated
security:
  - hasPermission:
      - deny
# definitions:
#
# Any definitions that are not yet used within paths/*.yml are automatically removed from the resulting swagger.yml.
# You may reference some definitions that you *always* want to be included here.
# --
