swagger: "2.0"
info:
  title: AuthDefinitions
  version: 0.0.0
paths: {}
definitions:
  User:
    type: object
    required:
      - id
    properties:
      id:
        type: string
        description: ID of user
        example: 891d37d3-c74f-493e-aea8-af73efd92016
      type:
        type: string
        description: Type of user
        example: admin
      roles:
        type: array
        description: Roles of user
        items:
          type: string
          example: admin
      email:
        type: string
        description: Email of user
        example: email@example.com
  LoginRequest:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        description: Email of user
      password:
        type: string
        description: Password of user
  LoginResponse:
    type: object
    properties:
      user_id:
        type: string
        description: ID of user
      access_token:
        type: string
        description: Access token
      refresh_token:
        type: string
        description: Refresh token
