consumes:
  - application/json
produces:
  - application/json
swagger: "2.0"
info:
  title: Application
  version: 0.2.0
basePath: /api
paths:
  /healthz/liveness:
    get:
      operationId: HealthLiveness
      responses:
        "200":
          description: success
      security:
        - {}
      description: Liveness probe
      tags:
        - health
      summary: Liveness probe for kubernetes health check. Returns 200 if the service
        is alive.
  /healthz/readiness:
    get:
      tags:
        - health
      summary: Readiness probe
      operationId: HealthReadiness
      responses:
        "503":
          description: Not available
          schema:
            $ref: '#/definitions/errorResponse'
        "200":
          description: success
      security:
        - {}
      description: "Readiness probe for kubernetes health check. Returns 200 if the
        service is ready to serve requests. \nReturns 503 if the service is not ready
        to serve requests (starting up or shutting down).\n"
  /v1/auth/check:
    get:
      tags:
        - auth
      summary: Check if the user is authenticated
      operationId: AuthCheckV1
      responses:
        "200":
          description: success
        "401":
          description: unauthorized
      security:
        - hasPermission:
            - auth:check
      description: |
        Check if the user is authenticated
  /v1/auth/login:
    post:
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/loginRequest'
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/loginRequest'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/failureResponse'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/errorResponse'
      security:
        - {}
      description: |
        Authenticates a user from a username and password and returns a JWT in the response and inside a
        signed cookie.
      tags:
        - auth
      summary: Login a user
      operationId: AuthLoginV1
  /v1/auth/logout:
    post:
      security:
        - {}
      description: |
        Invalidates an authenticated user's session and cookie
      tags:
        - auth
      summary: Logout the current user
      operationId: AuthLogoutV1
      responses:
        "200":
          description: success
definitions:
  errorResponse:
    type: object
    required:
      - status
      - message
    properties:
      code:
        type: integer
        maximum: !!float 599
        minimum: !!float 100
      data:
        type: object
      message:
        type: string
      status:
        enum:
          - error
        type: string
  failureResponse:
    type: object
    required:
      - status
      - data
    properties:
      data:
        type: object
      status:
        type: string
        enum:
          - fail
  loginRequest:
    type: object
    required:
      - email
      - password
    properties:
      email:
        description: Email of user
        type: string
      password:
        description: Password of user
        type: string
securityDefinitions:
  hasPermission:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://example.com
    tokenUrl: https://example.com
    scopes:
      auth:check: Check if the user is authenticated
security:
  - hasPermission:
      - deny
