consumes:
  - application/json
produces:
  - application/json
swagger: "2.0"
info:
  title: Application
  version: 0.2.0
paths:
  /healthz/readiness:
    get:
      security:
        - {}
      description: "Readiness probe for kubernetes health check. Returns 200 if the
        service is ready to serve requests. \nReturns 503 if the service is not ready
        to serve requests (starting up or shutting down).\n"
      tags:
        - health
      summary: Readiness probe
      operationId: HealthReadiness
      responses:
        "503":
          description: Not available
          schema:
            $ref: '#/definitions/errorResponse'
        "200":
          description: success
  /api/v1/auth/check:
    get:
      security:
        - hasPermission:
            - auth:check
      description: |
        Check if the user is authenticated
      tags:
        - auth
      summary: Check if the user is authenticated
      operationId: AuthCheck
      responses:
        "200":
          description: success
        "401":
          description: unauthorized
  /api/v1/auth/login:
    post:
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/loginRequest'
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/loginRequest'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/failureResponse'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/errorResponse'
      security:
        - {}
      description: |
        Authenticates a user from a username and password and returns a JWT in the response and inside a
        signed cookie.
      tags:
        - auth
      summary: Login a user
      operationId: AuthLogin
  /api/v1/auth/logout:
    post:
      summary: Logout the current user
      operationId: AuthLogout
      responses:
        "200":
          description: success
      security:
        - {}
      description: |
        Invalidates an authenticated user's session and cookie
      tags:
        - auth
  /healthz/liveness:
    get:
      description: Liveness probe
      tags:
        - health
      summary: Liveness probe for kubernetes health check. Returns 200 if the service
        is alive.
      operationId: HealthLiveness
      responses:
        "200":
          description: success
      security:
        - {}
definitions:
  errorResponse:
    type: object
    required:
      - status
      - message
    properties:
      code:
        minimum: !!float 100
        type: integer
        maximum: !!float 599
      data:
        type: object
      message:
        type: string
      status:
        type: string
        enum:
          - error
  failureResponse:
    type: object
    required:
      - status
      - data
    properties:
      status:
        type: string
        enum:
          - fail
      data:
        type: object
  loginRequest:
    required:
      - email
      - password
    properties:
      email:
        description: Email of user
        type: string
      password:
        description: Password of user
        type: string
    type: object
securityDefinitions:
  hasPermission:
    scopes:
      auth:check: Check if the user is authenticated
    type: oauth2
    flow: accessCode
    authorizationUrl: https://example.com
    tokenUrl: https://example.com
security:
  - hasPermission:
      - deny
